export const SeededData = [
    { id : 1, name : 'John', age : 25 },
    { id : 2, name : 'Jane', age : 30 },
    { id : 3, name : 'Bob', age : 35 },
    { id : 4, name : 'Alice', age : 20 },
    { id : 5, name : 'Mike', age : 40 },
    { id : 6, name : 'Emma', age : 45 },
    { id : 7, name : 'Tom', age : 50 },
    { id : 8, name : 'Lily', age : 55 },
    { id : 9, name : 'Jack', age : 60 },
    { id : 10, name : 'Olivia', age : 65 },
    { id : 11, name : 'William', age : 70 },
    { id : 12, name : 'Ava', age : 75 },
    { id : 13, name : 'James', age : 80 },
    { id : 14, name : 'Isabella', age : 85 },
    { id : 15, name : 'Robert', age : 90 },
    { id : 16, name : 'Sophia', age : 95 },
    { id : 17, name : 'Richard', age : 100 },
    { id : 18, name : 'Mia', age : 105 },
    { id : 19, name : 'Charles', age : 110 },
    { id : 20, name : 'Isabella', age : 115 },
];